Add wait during azure publishing
It seems that if we check the status too quickly, azure complains with the error:
ERROR: There is currently a pending copy operation.

So delay so the copy has a chance to start

Signed-off-by: Joseph Palermo <joseph.palermo@broadcom.com>
Co-authored-by: Joseph Palermo <joseph.palermo@broadcom.com>